import { jsPDF } from 'jspdf';
import {
  getItineraryDestinationCountry,
  getItineraryDestinationImage,
  getItineraryDestinationName,
  getItineraryMoodLabel,
} from '../features/results/itineraryNormalizer.js';

const PAGE_MARGIN = 40;
const PAGE_BOTTOM_RESERVED = 56;
const PAGE_LINE_HEIGHT = 14;
const HEADER_HEIGHT = 190;

function toSafeText(value, fallback = 'Not specified') {
  if (typeof value === 'string' && value.trim()) return value.trim();
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (Array.isArray(value) && value.length) return value.filter(Boolean).join(', ');
  return fallback;
}

function toDateLabel(value) {
  const date = value ? new Date(value) : new Date();
  if (Number.isNaN(date.getTime())) {
    return new Date().toISOString().slice(0, 10);
  }
  return date.toISOString().slice(0, 10);
}

function sanitizeFileSlug(value) {
  return toSafeText(value, '')
    .toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildFileName(itinerary) {
  const destinationName = getItineraryDestinationName(itinerary);
  const destinationCountry = getItineraryDestinationCountry(itinerary);
  const slug = sanitizeFileSlug([destinationName, destinationCountry].filter(Boolean).join(' '));
  return slug ? `travelmind-${slug}-itinerary.pdf` : 'travelmind-itinerary.pdf';
}

function formatDuration(stop) {
  if (!stop) return 'Not specified';
  if (typeof stop.durationLabel === 'string' && stop.durationLabel.trim()) return stop.durationLabel.trim();
  if (Number.isFinite(Number(stop.durationMinutes))) {
    const minutes = Number(stop.durationMinutes);
    if (minutes < 60) return `${Math.round(minutes)} min`;
    const hours = Math.floor(minutes / 60);
    const remaining = Math.round(minutes % 60);
    if (!remaining) return `${hours} h`;
    return `${hours} h ${remaining} min`;
  }
  return toSafeText(stop.duration, 'Not specified');
}

function formatCategory(category) {
  const text = toSafeText(category, 'activity');
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function formatTransport(transport) {
  if (Array.isArray(transport)) return transport.filter(Boolean).join(', ') || 'Not specified';
  return toSafeText(transport, 'Not specified');
}

function getBestTimeToVisit(itinerary) {
  return toSafeText(
    itinerary.bestTimeToVisit || itinerary.destination?.bestTimeToVisit || itinerary.meta?.bestTimeToVisit,
    'Not specified',
  );
}

function getTripSummary(itinerary) {
  return toSafeText(
    itinerary.subtitle || itinerary.summary || itinerary.destination?.description,
    'A tailored itinerary generated by TravelMind.',
  );
}

function getStopCount(itinerary) {
  return (Array.isArray(itinerary.days) ? itinerary.days : []).reduce((total, day) => (
    total + (Array.isArray(day.stops) ? day.stops.length : 0)
  ), 0);
}

function ensurePageSpace(doc, y, neededHeight, pageHeight) {
  if (y + neededHeight > pageHeight - PAGE_BOTTOM_RESERVED) {
    doc.addPage();
    return PAGE_MARGIN;
  }
  return y;
}

function getImageFormatFromDataUrl(dataUrl) {
  if (dataUrl.startsWith('data:image/png')) return 'PNG';
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP';
  return 'JPEG';
}

function loadImageAsDataUrl(url) {
  if (!url || url.startsWith('/')) return Promise.resolve(null);

  return fetch(url)
    .then((response) => {
      if (!response.ok) return null;
      return response.blob();
    })
    .then((blob) => (
      blob
        ? new Promise((resolve) => {
            const reader = new window.FileReader();
            reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : null);
            reader.onerror = () => resolve(null);
            reader.readAsDataURL(blob);
          })
        : null
    ))
    .catch(() => null);
}

function splitParagraph(doc, text, width) {
  return doc.splitTextToSize(toSafeText(text, 'No description available.'), width);
}

function renderFooter(doc, footerText) {
  const totalPages = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`${footerText} · Page ${pageNumber} of ${totalPages}`, pageWidth / 2, pageHeight - 18, { align: 'center' });
  }
}

function renderDestinationHeader(doc, itinerary, imageDataUrl, destinationLabel, pageWidth) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, HEADER_HEIGHT, 'F');

  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, getImageFormatFromDataUrl(imageDataUrl), 0, 0, pageWidth, HEADER_HEIGHT);
    } catch {
      doc.setFillColor(15, 23, 42);
      doc.rect(0, 0, pageWidth, HEADER_HEIGHT, 'F');
    }
  }

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth * 0.66, HEADER_HEIGHT, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(248, 250, 252);
  doc.text('TravelMind Itinerary', PAGE_MARGIN, 48);

  doc.setFontSize(28);
  doc.text(splitParagraph(doc, destinationLabel, pageWidth - (PAGE_MARGIN * 2)), PAGE_MARGIN, 88);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(226, 232, 240);
  doc.text(splitParagraph(doc, getTripSummary(itinerary), pageWidth - (PAGE_MARGIN * 2)), PAGE_MARGIN, 132);

  return HEADER_HEIGHT + 30;
}

function renderMetadataPanel(doc, rows, y, contentWidth, pageHeight) {
  const columnGap = 18;
  const columnWidth = (contentWidth - columnGap) / 2;
  const rowHeight = 38;
  const panelHeight = 28 + (Math.ceil(rows.length / 2) * rowHeight);
  y = ensurePageSpace(doc, y, panelHeight, pageHeight);

  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundRect(PAGE_MARGIN, y, contentWidth, panelHeight, 12, 12, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text('Trip Metadata', PAGE_MARGIN + 14, y + 20);

  rows.forEach((row, index) => {
    const column = index % 2;
    const line = Math.floor(index / 2);
    const x = PAGE_MARGIN + 14 + (column * (columnWidth + columnGap));
    const rowY = y + 44 + (line * rowHeight);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(row.label.toUpperCase(), x, rowY);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(splitParagraph(doc, toSafeText(row.value), columnWidth), x, rowY + 13);
  });

  return y + panelHeight + 22;
}

function drawSectionHeading(doc, title, subtitle, y, width, pageHeight) {
  const lineCount = subtitle ? 2 : 1;
  y = ensurePageSpace(doc, y, 30 + (lineCount * PAGE_LINE_HEIGHT), pageHeight);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(title, PAGE_MARGIN, y);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100);
    const lines = splitParagraph(doc, subtitle, width);
    doc.text(lines, PAGE_MARGIN, y + 16);
    y += 16 + (lines.length * PAGE_LINE_HEIGHT);
  } else {
    y += 22;
  }

  return y;
}

function renderStop(doc, stop, y, contentWidth, pageHeight) {
  const titleLines = splitParagraph(doc, `${toSafeText(stop.arrivalTime, 'Flexible')}  ${toSafeText(stop.name, 'Unnamed stop')}`, contentWidth - 24);
  const categoryLine = `Category: ${formatCategory(stop.category)} | Duration: ${formatDuration(stop)}`;
  const categoryLines = splitParagraph(doc, categoryLine, contentWidth - 24);
  const descriptionLines = splitParagraph(doc, stop.description, contentWidth - 24);
  const travelLines = stop.travelToNext ? splitParagraph(doc, `Next transfer: ${stop.travelToNext}`, contentWidth - 24) : [];
  const blockHeight = 22 + (titleLines.length * 12) + (categoryLines.length * 11) + (descriptionLines.length * 12) + (travelLines.length * 11) + 28;

  y = ensurePageSpace(doc, y, blockHeight, pageHeight);

  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundRect(PAGE_MARGIN, y, contentWidth, blockHeight, 14, 14, 'FD');

  let innerY = y + 18;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(titleLines, PAGE_MARGIN + 12, innerY);
  innerY += titleLines.length * 12 + 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(categoryLines, PAGE_MARGIN + 12, innerY);
  innerY += categoryLines.length * 11 + 4;

  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  doc.text(descriptionLines, PAGE_MARGIN + 12, innerY);
  innerY += descriptionLines.length * 12 + 6;

  if (travelLines.length) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(travelLines, PAGE_MARGIN + 12, innerY);
  }

  return y + blockHeight + 10;
}

export async function exportItineraryToPdf(itinerary) {
  if (!itinerary) {
    throw new Error('No itinerary available to export.');
  }

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (PAGE_MARGIN * 2);
  const pageHeight = doc.internal.pageSize.getHeight();
  const generationDate = toDateLabel(itinerary.generatedAt);
  const footerText = `Generated with TravelMind · ${generationDate}`;

  const destinationName = getItineraryDestinationName(itinerary);
  const destinationCountry = getItineraryDestinationCountry(itinerary);
  const destinationLabel = destinationCountry ? `${destinationName}, ${destinationCountry}` : destinationName;
  const imageDataUrl = await loadImageAsDataUrl(getItineraryDestinationImage(itinerary));
  let y = renderDestinationHeader(doc, itinerary, imageDataUrl, destinationLabel, pageWidth);

  y = renderMetadataPanel(doc, [
    { label: 'Destination', value: destinationLabel },
    { label: 'Travel Style', value: getItineraryMoodLabel(itinerary) },
    { label: 'Duration', value: itinerary.duration },
    { label: 'Radius', value: itinerary.radius },
    { label: 'Best Time', value: getBestTimeToVisit(itinerary) },
    { label: 'Budget', value: itinerary.budget },
    { label: 'Transport', value: formatTransport(itinerary.transport) },
    { label: 'Travelers', value: `${toSafeText(itinerary.adults, '1')} adults, ${toSafeText(itinerary.children, '0')} kids` },
    { label: 'Stops', value: getStopCount(itinerary) },
    { label: 'Generated', value: generationDate },
  ], y, contentWidth, pageHeight);

  const days = Array.isArray(itinerary.days) ? itinerary.days : [];
  if (!days.length) {
    y = ensurePageSpace(doc, y, 40, pageHeight);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105);
    doc.text('No itinerary details available.', PAGE_MARGIN, y + 10);
    y += 28;
  } else {
    y += 8;
    days.forEach((day) => {
      const dayTitle = `Day ${toSafeText(day.day, '')}${day.title ? `: ${day.title}` : ''}`;
      const stopCount = Array.isArray(day.stops) ? day.stops.length : 0;
      const daySubtitle = `${stopCount} stop${stopCount === 1 ? '' : 's'} planned`;
      y = drawSectionHeading(doc, dayTitle, daySubtitle, y, contentWidth, pageHeight);

      const stops = Array.isArray(day.stops) ? day.stops : [];
      stops.forEach((stop) => {
        y = renderStop(doc, stop, y, contentWidth, pageHeight);
      });

      y += 2;
    });
  }

  renderFooter(doc, footerText);
  doc.save(buildFileName(itinerary));
}
